name: app_write_clone
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  auto_route: ^7.8.4
  flutter_bloc: ^8.1.3
  provider: ^6.0.0

  user_repository:
    path: packages/user_repository

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
 
  assets:
     - assets/icons/
     - assets/images/

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
